- en_US.json
- index.json
translations for https://github.com/YimMenu/YimMenu/pull/1029
> feat(cmd_executor): add translations

- en_US.json
- index.json
for https://github.com/YimMenu/YimMenu/pull/1029
sorry for the 2nd pr
> fix(cmd_executor): add translation for multiple commands

- en_US.json
refer to [#1156](https://github.com/YimMenu/YimMenu/pull/1156)
> game cache trans

- en_US.json
- index.json
Added custom teleport for https://github.com/YimMenu/YimMenu/pull/1652
> Added GUI_TAB_CUSTOM_TELEPORT

- en_US.json
- es_ES.json
- fr_FR.json
- index.json
- pt_BR.json
- zh_CN.json
nightly `f26514f8e459ca65ac62f16b00962ba8a0f1178b`
> quick fix for "Saved profiles"

- en_US.json
- index.json
- zh_CN.json
this was spotted in the [menu](https://github.com/YimMenu/YimMenu/pull/1331#discussion_r1218520968) but not in [translations](https://github.com/YimMenu/Translations/pull/34)
> fix: `RECEIVE_PICKUP` typo 

- .github/workflows/check-deprecated-keys.yml
This Github action needs to be manually triggered, it'll check if any of the translation keys in `en_US.json` which should be the most up-to-date translation.
This will help us in the following ways:
- Remove deprecated keys of old features
- Verify that all translation keys have been implemented properly.
> Check if the translation repository contains any unused keys

- index.json
This PR adds some additional fields to the index file to indicate which alphabet type is required to display the font.
> Dynamic font loading testing

- fr_FR.json
- index.json
Small oversight which is probably the cause of the French translation not working?
> Small correction of the fr_FR.json

- en_US.json
Translations for https://github.com/YimMenu/YimMenu/pull/3003
"VEHICLE_INFINITE_AMMO": "Vehicle Infinite Ammo",
"VEHICLE_INFINITE_AMMO_DESC": "Infinite vehicle rockets, bombs, and countermeasures",
> Translations for Vehicle Infinite Ammo

- en_US.json
Translation for https://github.com/YimMenu/YimMenu/pull/3004
> Vehicle Controller Description

- en_US.json
- index.json
Translations for https://github.com/YimMenu/YimMenu/pull/3000
> Added "Enable MK1 and MK2 Weapons" feature.

- en_US.json
Text to accompany a new start script allowed notification feature in https://github.com/YimMenu/YimMenu/pull/3045
> REACTION_START_SCRIPT_NOTIFY

- en_US.json
- index.json
Translations for https://github.com/YimMenu/YimMenu/pull/3139.
> Translations for metric filtering system.

- en_US.json
Translations for [YimMenu#3192](https://github.com/YimMenu/YimMenu/pull/3192)
> For YimMenu#3192

- en_US.json
- index.json
Notification message to inform a user that first-person view with vehicle flymode is currently unsupported.
https://github.com/YimMenu/YimMenu/pull/2991
> FPV Vehicle Fly Notification

- en_US.json
- index.json
Translation for https://github.com/YimMenu/YimMenu/pull/3408
> Translation for Outfit Editor Tip

- en_US.json
- index.json
Translations for https://github.com/YimMenu/YimMenu/pull/3430
> Use Weapon's Max Range

- en_US.json
- index.json
Translations for https://github.com/YimMenu/YimMenu/pull/3484
> Colors type

- en_US.json
- index.json
Translations for https://github.com/YimMenu/YimMenu/pull/3550
> Aimbot threat translations.

- en_US.json
- index.json
Translation for https://github.com/YimMenu/YimMenu/pull/3612
> Translation for Script Patches

- en_US.json
Translation for https://github.com/YimMenu/YimMenu/pull/3667
> Translation for HTTP Start Request Log
